
Kind: PersistentVolume
apiVersion: v1
metadata:
  name: airflow-dags
  namespace: airflow
spec:
  capacity:
    storage: 16Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  mountOptions:
    - hard
    - nfsvers=4.1
    - rsize=1048576
    - wsize=1048576
    - timeo=600
    - retrans=2
  nfs:
    path: /
    server: fs-xxxxxx.efs.us-east-1.amazonaws.com
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: airflow-logs
  namespace: airflow
spec:
  capacity:
    storage: 16Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  mountOptions:
    - hard
    - nfsvers=4.1
    - rsize=1048576
    - wsize=1048576
    - timeo=600
    - retrans=2
  nfs:
    path: /
    server: fs-xxxxxx.efs.us-east-1.amazonaws.com
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: airflow-dags
  namespace: airflow
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  resources:
    requests:
      storage: 8Gi
  volumeName: airflow-dags
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: airflow-logs
  namespace: airflow
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  resources:
    requests:
      storage: 8Gi
  volumeName: airflow-logs
